# Generated by Django 3.2.3 on 2021-07-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_blogpost_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='id',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_slug',
            field=models.SlugField(default='test', primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
