# Generated by Django 3.2.3 on 2021-08-13 03:45

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20210725_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('title_slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('ongoing', models.BooleanField(default=False)),
                ('main_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('color', colorfield.fields.ColorField(default='#0099cc', max_length=18)),
                ('post_ref', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.blogpost')),
            ],
        ),
    ]
