# Generated by Django 3.2.9 on 2021-11-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20210813_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttag',
            name='post_ref',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(to='homepage.PostTag'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='associated_posts',
            field=models.ManyToManyField(to='homepage.BlogPost'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='main_image',
            field=models.ImageField(upload_to='public/portfolioimages'),
        ),
    ]
