# Generated by Django 3.2.9 on 2021-11-19 19:47

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_blogpost_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttag',
            name='text_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
